[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_ENV = "production"

[[edge_functions]]
  path = "/*"
  function = "inject-meta"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Path = ["/"]}

[[headers]]
  for = "/index.html"
    [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache"
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.googleapis.com https://*.gstatic.com https://*.google.com 'unsafe-inline' 'unsafe-eval'; img-src 'self' https://*.googleapis.com https://*.gstatic.com https://*.google.com https://porto-map.netlify.app data:; font-src 'self' https://fonts.gstatic.com data:;"

[[headers]]
  for = "/static/js/*"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/static/css/*"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/porto.jpeg"
    [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "ALLOWALL"

[[headers]]
  for = "/*.jpeg"
    [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.jpg"
    [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*" 